[package]
name = "rustendo64"
version = "0.1.0"
authors = ["ferris <jake@fusetools.com>"]
license = "MIT/Apache-2.0"

[dependencies]
byteorder = "0.4.2"
num = "0.1.30"
enum_primitive = "0.1.0"
nom = "^1.2.3"